### ISSUE TITLE
segfault if >275k cells

### ISSUE THREAD

**Issue by WandrilleD** [jmbreda/Sanity#1]
Hi,
first off, thank you for this useful and easy to use software.

I was testing it out on some data and I found out that whenever the number of cells was above something like 275k cells the allocation on line 59 of calc_true_variation_parallel_prior_mu_sigma.cpp would result in a segfault.

cheers.

**Comment by jmbreda** [comment]
Hi,

Thank you for pointing this out. This memory allocation issue should be fixed now, let me know if it works.

Best.
