### ISSUE TITLE
Error in simulation code

### ISSUE THREAD

**Issue by cakeinspace** [jmbreda/Sanity#20]
I was trying to run the simulation code in the reproducibility folder and there are two errors one is the presence of a variable called SC which i replaced with T another which I haven't been able to solve is the N_c.*exp(E) where the error is incorrect matrix dimensions. Can you please make corrections to the script or tell me what the correct line should be.

Thanks 
Anurag

**Comment by jmbreda** [comment]
Hi Anurag,

Thanks for this, I fixed the bug.

Best
Jeremie
