### ISSUE TITLE
not enough fields on line number 0

### ISSUE THREAD

**Issue by qiaochen** [jmbreda/Sanity#6]
Hello, thank you for releasing your work. I was trying to test your wonderful tool on [3k PBMC](http://cf.10xgenomics.com/samples/cell-exp/1.1.0/pbmc3k/pbmc3k_filtered_gene_bc_matrices.tar.gz) dataset. It was a .mtx matrix, and running Sanity encountered an error showing "not enough fields on line number 0". Is Sanity trying to read the headlines?

**Comment by jmbreda** [comment]
Hi qiaochen, thank you for your interest in Sanity. Sanity ignore the first commented lines (starting with `%`), then expect in the first non-commented line total number of gene IDs, total number of cells IDs, total nubmer of rows (see https://math.nist.gov/MatrixMarket/formats.html for details on .mtx files). However this error seems to indicate the Sanity did not recognize the mtx format of the input. Is your input file extension `.mtx`? Is is it decompressed?

**Comment by qiaochen** [comment]
Many thanks, Breda! Indeed, the problem lies in the .mtx file, which was not completely transferred due to an unsuccessful scp command.
